name: new_timeseries_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - alsa-lib=1.2.12
  - annotated-types=0.7.0
  - anyio=4.4.0
  - archspec=0.2.3
  - attr=2.5.1
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.8.0
  - azure-storage-blobs-cpp=12.12.0
  - azure-storage-common-cpp=12.7.0
  - azure-storage-files-datalake-cpp=12.11.0
  - blas=1.0
  - bokeh=3.5.2
  - boltons=24.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.33.1
  - ca-certificates=2024.8.30
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2024.8.30
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - conda=24.7.1
  - conda-libmamba-solver=24.7.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - contourpy=1.3.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cudatoolkit=11.8.0
  - cycler=0.12.1
  - cytoolz=0.12.3
  - dask=2024.6.2
  - dask-core=2024.6.2
  - dask-expr=1.1.6
  - dbscan=0.0.12
  - dbus=1.13.6
  - distributed=2024.6.2
  - distro=1.9.0
  - dm-tree=0.1.8
  - exceptiongroup=1.2.2
  - expat=2.6.2
  - ffmpeg=4.3
  - filelock=3.15.4
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.1
  - freetype=2.12.1
  - frozendict=2.4.4
  - fsspec=2024.6.1
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.1.5
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - harfbuzz=8.5.0
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.2
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.8
  - importlib-metadata=8.4.0
  - importlib_metadata=8.4.0
  - jinja2=3.1.4
  - jiter=0.5.0
  - joblib=1.4.2
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang13=18.1.7
  - libcrc32c=1.1.2
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.9.1.3
  - libcups=2.3.3
  - libcurand=10.3.5.147
  - libcurl=8.8.0
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgcrypt=1.11.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.2
  - libgomp=14.1.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgpg-error=1.50
  - libgrpc=1.62.2
  - libhwloc=2.11.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm15=15.0.7
  - libllvm18=18.1.7
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libnpp=11.8.0.86
  - libnsl=2.0.1
  - libnvjpeg=11.9.0.86
  - libogg=1.3.5
  - libopenblas=0.3.27
  - libopus=1.3.1
  - libparquet=16.1.0
  - libpng=1.6.43
  - libpq=16.4
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsolv=0.7.29
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libsystemd0=256.5
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libutf8proc=2.8.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - llvmlite=0.42.0
  - locket=1.0.0
  - lz4=4.3.3
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - menuinst=2.1.2
  - mkl=2022.2.1
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.6
  - mpmath=1.3.0
  - msgpack-python=1.0.8
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-libs=8.3.0
  - namex=0.0.8
  - ncurses=6.5
  - nettle=3.6
  - networkx=3.3
  - nspr=4.35
  - nss=3.100
  - numba=0.59.1
  - numpy=1.26.4
  - openai=1.42.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.3.2
  - orc=2.0.1
  - packaging=24.1
  - pandas=2.2.2
  - partd=1.4.2
  - patsy=0.5.6
  - pcre2=10.43
  - pillow=10.3.0
  - pip=24.2
  - pixman=0.43.2
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - ply=3.11
  - psutil=6.0.0
  - pthread-stubs=0.4
  - pulseaudio-client=17.0
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pyarrow-hotfix=0.6
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pygments=2.18.0
  - pyparsing=3.1.4
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytorch=2.4.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2024.1
  - pywavelets=1.6.0
  - pyyaml=6.0.2
  - qt-main=5.15.8
  - re2=2023.09.01
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.32.3
  - rich=13.7.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - s2n=1.4.15
  - scikit-learn=1.5.1
  - scipy=1.14.0
  - setuptools=73.0.1
  - sip=6.7.12
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - statsmodels=0.14.2
  - stumpy=1.13.0
  - sympy=1.13.2
  - tbb=2021.12.0
  - tblib=3.0.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.1
  - torchaudio=2.4.1
  - torchtriton=3.0.0
  - torchvision=0.19.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - truststore=0.9.2
  - tsfresh=0.20.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - urllib3=2.2.2
  - wheel=0.44.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxxf86vm=1.1.5
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2024.9.0
  - xz=5.2.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zict=3.0.0
  - zipp=3.20.1
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - astunparse==1.6.3
      - cudatools==0.0.1
      - cython==0.29.37
      - fastdtw==0.3.4
      - flatbuffers==24.3.25
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.66.1
      - hdbscan==0.8.38.post1
      - keras==3.5.0
      - libclang==18.1.1
      - markdown==3.7
      - matplotlib==3.9.2
      - opt-einsum==3.4.0
      - optree==0.12.1
      - plotly==5.22.0
      - protobuf==4.25.5
      - pynndescent==0.5.13
      - python-graphviz==0.20.3
      - scikit-base==0.11.0
      - scikit-learn-extra==0.3.0
      - seaborn==0.13.2
      - sktime==0.34.0
      - tenacity==8.5.0
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - termcolor==2.4.0
      - tslearn==0.6.3
      - umap-learn==0.5.6
      - visdom==0.2.4
      - websocket-client==1.8.0
      - werkzeug==3.0.4
      - wrapt==1.16.0
prefix: /home/emarinho/miniconda3/envs/new_timeseries_env
